# Generated by Django 2.0.1 on 2018-01-28 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiAuth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertType', models.CharField(default='', max_length=20)),
                ('alertTime', models.DateTimeField(default='')),
                ('alertDetails', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceFK', to='apiAuth.Device')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='alertsFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertsFK', to='devices.Alerts'),
        ),
    ]
