# Generated by Django 2.0.1 on 2018-01-28 02:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('apiAuth', '0002_auto_20180128_0248'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['alertTime']},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alertsFK',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='deviceFK',
        ),
        migrations.AddField(
            model_name='alert',
            name='alerts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.Alerts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerts',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='apiAuth.Device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='alertTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
