# Generated by Django 2.0.1 on 2018-01-28 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180128_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='apiAuth.Device'),
        ),
    ]
