# Generated by Django 2.0.1 on 2018-01-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20180128_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='uid',
            field=models.CharField(default='', max_length=16),
        ),
    ]
