# Generated by Django 2.0.1 on 2018-01-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alerts_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='uid',
        ),
        migrations.AddField(
            model_name='alert',
            name='uid',
            field=models.CharField(default='', max_length=16),
        ),
    ]
