# Generated by Django 2.0.1 on 2018-01-29 05:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0002_auto_20180128_0248'),
        ('devices', '0007_auto_20180128_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('altitude', models.DecimalField(decimal_places=6, max_digits=16, null=True)),
                ('alertTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_device', to='apiAuth.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accel_x', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('accel_y', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('accel_z', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_device', to='apiAuth.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='alertDetails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alertTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alertType',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='uid',
            field=models.CharField(default='ec656082-084e-4b1a-868e-8d8ddfa7af36', max_length=40, unique=True),
        ),
    ]
