# Generated by Django 2.0.1 on 2018-01-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20180129_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='uid',
            field=models.CharField(default='9ada9c2a-1c0f-4805-b2da-e6bc1b3d6a79', max_length=40, unique=True),
        ),
    ]
