# Generated by Django 2.0.1 on 2018-03-16 20:51

import devices.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0002_auto_20180128_0248'),
        ('devices', '0009_auto_20180129_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, default='', upload_to=devices.models.user_directory)),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media_device', to='apiAuth.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netNum', models.CharField(blank=True, default='', max_length=4)),
                ('ssid', models.CharField(blank=True, default='', max_length=48)),
                ('psk', models.CharField(blank=True, default='', max_length=48)),
                ('netType', models.CharField(blank=True, default='', max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networkList_device', to='apiAuth.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, unique=True)),
                ('frontEnable', models.BooleanField(default=False)),
                ('rearEnable', models.BooleanField(default=False)),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stream_device', to='apiAuth.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='network',
            name='networkList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networkList', to='devices.NetworkList'),
        ),
    ]
