# Generated by Django 2.0.1 on 2018-03-19 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0002_auto_20180128_0248'),
        ('devices', '0010_auto_20180316_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('command', models.CharField(blank=True, default='', max_length=128)),
                ('priority', models.IntegerField(default=1)),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_device', to='apiAuth.Device')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['netNum']},
        ),
        migrations.AlterField(
            model_name='network',
            name='netNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('networkList', 'netNum')},
        ),
    ]
