# Generated by Django 2.0.1 on 2018-03-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20180319_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-netNum']},
        ),
    ]
