# Generated by Django 2.0.1 on 2018-03-20 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20180320_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
