# Generated by Django 2.0.1 on 2018-04-05 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0002_auto_20180128_0248'),
        ('devices', '0013_event_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accel_x', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('accel_y', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('accel_z', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('statTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_device', to='apiAuth.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='device',
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
